config/routes.rb
Rails.application.routes.draw do
  devise_for :users
    resources :user_goals , only: [:new, :create, :destroy, :show]
    resources :budgets do
      resources :cash_flows , shallow: true
    end

    authenticated :user do
      root 'users#balance', as: :authenticated_root
    end
  root to: 'pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/salary' ,to: 'users#salary'
  patch '/salary', to: "users#save_salary"
  get '/balance', to:"users#balance"
  get '/dashboard' ,to: 'users#dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/budget.rb
class Budget < ApplicationRecord
  belongs_to :user
  belongs_to :category
  monetize :amount_cents

  has_many :cash_flows ,dependent: :destroy
  #validates_uniqueness_of :category_id, scope: :category


  def spent
    self.cash_flows.sum(:price_cents)
  end

  def remaining
    self.amount.to_i - self.spent
  end
end

app/models/cash_flow.rb
class CashFlow < ApplicationRecord
  belongs_to :user
  belongs_to :budget
  monetize :price_cents
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/goal.rb
class Goal < ApplicationRecord
has_many :users, through: :user_goals
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :budgets
  has_many :cash_flows
  has_many :goals, through: :user_goals
end

app/models/user_goal.rb
class UserGoal < ApplicationRecord
  belongs_to :user
  belongs_to :goal
  monetize :amount_cents

  validates :goal_id, presence: { scope: :goal}
  validates :amount_cents, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  def after_sign_in_path_for(resource)
  	new_user_goal_path
end

def default_url_options
  { host: ENV["HOST"] || "localhost:3000" }
end
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController

  	before_action :set_budget, only: [:show, :edit, :update, :destroy]

  def index
    @budgets = Budget.find(current_user.budget_ids)
    @categories = []
    @budgets.map do |budget|
      @categories.push(Category.where(id: budget.category_id))
      end # GET /budgets
  end

  def show
  raise     # GET /budgets/:id
  	@budget = Budget.find(params[:id])
   @cash_flows = @budget.cash_flows
  end


  def new
    @categories = Category.all
  	@budget = Budget.new
  end

  def create        # POST /budgets
  	@budget = Budget.new(budget_params)
  	@budget.user = current_user
    @budget.Budget_balance = 0
    if @budget.save!
    	redirect_to budgets_path(@budget)
    else
    	render :new
  	end
  end

  def edit          # GET /budgets/:id/edit
  	@budget = Budget.find(params[:id])
  end

  def update        # PATCH /budgets/:id
  	@budget = Budget.find(params[:id])
    @budget.update(budget_params)
  end

  def destroy       # DELETE /budgets/:id

    @budget.destroy
    redirect_to budgets_path
  end


 private
  def budget_params
    params.require(:budget).permit(:name, :description, :amount_cents, :start_date ,:end_date ,:category_id)
  end

    def set_budget
    @budget = Budget.find(params[:id])
  end
end

app/controllers/cash_flows_controller.rb
class CashFlowsController < ApplicationController

      before_action :set_cashflow, only: [:show, :edit, :update, :destroy]

  def index
    @cash_flows = CashFlow.find(current_user.cash_flow_ids)
  # GET /budgets
  end

  def show         # GET /budgets/:id
  	@cash_flow = CashFlow.find(params[:id])
  end

  def new
    if current_user.budgets.present?         # GET /budgets/new
    	@cash_flow = CashFlow.new
      @budgets = Budget.where(user_id: current_user.id)
      @categories = []
      @budgets.each { |budget| @categories.push(Category.find(budget.category_id))}
    else
      redirect_to controller: 'budgets', action: 'new'
    end

  end


  def create        # POST /budgets
  	@cash_flow = CashFlow.new(cashflow_params)
  	@cash_flow.user = current_user
    @budget = Budget.find(@cash_flow.budget_id)
    # @budget.Budget_balance = 0
    # @budget.Budget_balance += @cash_flow.price_cents
    current_user.balance -= @cash_flow.price_cents
    current_user.save!

    if params[:cash_flow][:price_cents].to_i < @cash_flow.budget.remaining
      @cash_flow.save!
    	redirect_to balance_path(@cash_flow.budget)
    else
      @budgets = Budget.where(user_id: current_user.id)
    	render :new
      flash[:alert] = 'Expense have a date, category, and be within your set budget'
  	end
  end

  def edit

  end

   def update        # PATCH /budgets/:id
  	@cash_flow = CashFlow.find(params[:id])
    @cash_flow.update(cashflow_params)
    redirect_to budget_cash_flows_path(@cash_flow.budget)
  end

  def destroy
    @cash_flow.destroy
    redirect_to budget_cash_flows_path(@cash_flow.budget)
  end



 private
  def cashflow_params
    params.require(:cash_flow).permit(:price_cents,:date,:budget_id)
  end

    def set_cashflow
    @cash_flow = CashFlow.find(params[:id])
  end


end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :set_goal

  def new
    @goal = Goal.new
  end

  def index
    @goals = Goal.find(current_user.goal_ids)    # GET /budgets
  end

 private

  def goal_params
    params.require(:goal).permit(:name, :image_goal )
  end

  def set_goal
    @goal = Goal.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/user_goals_controller.rb
class UserGoalsController < ApplicationController
  before_action :set_user_goal, only: [:show,  :update, :destroy]




  def new
  #
    @user_goal = UserGoal.new

  end

  def show         # GET /budgets/:id
    @user_goal = UserGoal.find(params[:id])
  end


  def create
    @user_goal = UserGoal.new(user_goal_params)
    @user_goal.user = current_user
    if params[:user_goal][:goal_id] != ''
      @goal = Goal.find(params[:user_goal][:goal_id])
      @user_goal.goal = @goal
      @user_goal.save!
      redirect_to salary_path(@user_goal)
    else
      render :new
      flash[:alert] = 'Please specify your goal and its price!'
    end
  end





  def destroy
    @user_goal.destroy
    redirect_to budget_cash_flows_path
  end


 private
  def user_goal_params
    params.require(:user_goal).permit(:user_id,:goal_id,:amount_cents )
  end

    def set_user_goal
      @user_goal = UserGoal.find(params[:id])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController



	 def salary
	    # @user.salary = current_user.salary
	    @user = current_user
	 end

	 def save_salary
	    @user = current_user

		@user.update(salary_params)
		@user.balance = @user.salary
		@user.save!
		redirect_to balance_path

	end

	def balance
	    @budget = Budget.new
      @user = current_user
	end

	def dashboard
	   @budgets = current_user.budgets
	   @budgets = Budget.where(user_id: current_user.id)
	   @user_goal = UserGoal.where({user_id: current_user.id})[0]
	   @goal = Goal.find(@user_goal.goal_id)

     @goal_percent = ((current_user.balance.to_f / @user_goal.amount_cents.to_f)* 100)
     @giphy_url = generate_giphy_url(@goal_percent)
	end

def generate_giphy_url(goal_percent)
  @goal_percent = goal_percent
  #if goal_percent < 50% -- sad gif
  if goal_percent < 10
    @response = Giphy.random('where is my money')
    return @response.image_url

  elsif goal_percent < 70 && goal_percent > 10
    @response = Giphy.random('make it rain')
    return @response.image_url

  else
    #else happy gif
    @response = Giphy.random('make it rain')
    return @response.image_url
  end
end


private




	 def salary_params
	    params.require(:user).permit(:salary,:balance)
	 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
# app/helpers/meta_tags_helper.rb

module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/budgets/_show.html.erb
<div class="chart-info">
<p4>You've already spent: $<%= budget.spent%></p4>
<br>
<p4>You still have: $<%= budget.remaining %></p4>
<%= pie_chart(
        {"Money Left" => "#{budget.remaining}", "Money Spent" => "#{budget.spent}"},
        colors: ["#83a3a5", "#183287"],
        donut: true,
        prefix: "$",
        legend: "bottom",
        )%>
</div>

app/views/budgets/edit.html.erb
<h1>Editing budget</h1>

<div class="container">
	<div class="row">
		<div class="col-xs-offset-3 col-xs-6">
			<%= simple_form_for [@budget] do |f| %>
			  <%= f.input :name, label: "Budget name"  %>
			  <%= f.input :description  %>
			  <%= f.input :start_date  %>
			  <%= f.input :end_date  %>
			  <%= f.input :amount_cents  %>
			  <%= f.input :category_list ,as: :radio_buttons, collection:["Food & Drink","Bills & Fees", "Car", "Education", "Transport", "Clothes", "Home", "Entertainment","Healthcare"] %>
			  <%= f.submit %>
			<% end %>
			
		</div>
	</div>
</div>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-3 col-xs-6">
			<h1>budgets</h1>

            <table>
			  <thead>
			    <tr>
			      <th>Category_list</th>
			      <th>Description</th>
			      <th>Amount</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>
			    <tbody>
				<% @budgets.each do |budget| %>
				<tr>
				<td><%= image_tag(Category.find_by(id: budget.category_id).photo) %></td>
				<td><%= budget.description %></td>
				<td><%= budget.amount_cents %></td>
				<td><%= link_to 'Show', budget %></td>
		        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
		        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
			    </tr>
			   </tbody> 
		    </table>
		    <br>
            <%= link_to 'New budget', new_budget_path %>
		</div>
	</div>
</div>

app/views/budgets/new.html.erb
<div class="container">
	<div class="row">
		<div class="col col-xs-12 budget-form">
			<%= simple_form_for [@budget] do |f| %>
        <%= f.input :amount_cents, label: 'How much do you want to spend?', error: 'This field is mandatory',  placeholder: 'Enter the amount'  %>
			  <%= f.input :description, label: false, placeholder: 'Description'  %>
			  <%= f.input :start_date, as: :string, label: 'Starting date', input_html: { id: "range_start" }  %>
			  <%= f.input :end_date, as: :string, label: 'Ending date', input_html: { id: "range_end" }  %>

			  # <%= f.association :category,  as: :radio_buttons, input_html: {class: "hide-checkbox"},label_html: {style: "width: auto; min-width:0;"}, label: 'Choose a category:', collection: @categories.map { |e| [image_tag(e.photo),e.id] } %>
			  <%= f.button :submit, "Add", class: "add-button" %>
			<% end %>
		</div>
	</div>
</di

app/views/cash_flows/edit.html.erb
<h1>Editing Cash Flow</h1>

<div class="container">
	<div class="row">
		<div class="col-xs-offset-3 col-xs-6">
			<%= simple_form_for @cash_flow do |f| %>
			  <%= f.input :price_cents, label: "Amount" %>
			  <%= f.input :date  %>
		      <%= f.association :budget, collection: current_user.budgets, label_method: :category_list %>
			  <%= f.submit %>
			<% end %>

		</div>
	</div>
</div>

<%= link_to 'Show', @cash_flow %>
<%= link_to 'Back', root_path %>

app/views/cash_flows/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-offset-3 col-xs-6">
			<h1>Cash Flow</h1>

            <table>
			  <thead>
			    <tr>
			      <th>Budget</th>
			      <th>Date</th>
			      <th>Amount</th>
			      <th colspan="3"></th>
			    </tr>
			  </thead>
			    <tbody>
				<% @cash_flows.each do |cash_flow| %>
        <tr>
				<td><%= cash_flow.budget.category.name %></td>
				<td><%= cash_flow.date %></td>
				<td><%= cash_flow.price_cents %></td>
				<td><%= link_to 'Show', cash_flow %></td>
		        <td><%= link_to 'Edit', edit_cash_flow_path(cash_flow) %></td>
		        <td><%= link_to 'Destroy', cash_flow, method: :delete, data: { confirm: 'Are you sure?' } %></td>
				<% end %>
			    </tr>
			   </tbody>
		    </table>
		    <br>
            <%= link_to 'New Cash Flow', new_budget_cash_flow_path %>
		</div>
	</div>
</div>

app/views/cash_flows/new.html.erb
<div class="container">
	<div class="row cashflow-wrapper">
		<div class="col-xs-offset-1 col-xs-10">
			<%= simple_form_for(@cash_flow, method: :post, url: budget_cash_flows_path) do |f| %>
				<%= f.input :price_cents, label: "Add a new expense ($)", as: :string %>
				<%= f.input :date, as: :string,  input_html: {class: "datepicker"}  %>

        <%= f.association :budget,  as: :radio_buttons, input_html: {class: "hide-checkbox"},label_html: {style: "width: auto; min-width:0;"}, label: 'Choose a category:', collection: @budgets.map { |e| [image_tag(e.category.photo),e.id] }%>
				<%= f.submit "Submit", :class => "submit_btn" %>
			<% end %>
		</div>
	</div>
</div>



<script>
  icon_targets = document.querySelectorAll(".form-check label");
  icon_targets.forEach((element) => {
    element.classList.add("icon-resting");
    element.addEventListener("click", ()=>{
      icon_targets.forEach(element =>
         element.classList.remove('icon-active'));
      element.classList.add('icon-active');
    })
  })
</script>

app/views/cash_flows/show.html.erb
<h1>Show my cash flow</h1>

app/views/goals/index.html.erb
<h1>Goals</h1>

app/views/goals/new.html.erb
<h1> new goal</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Budgetly</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.5.0/css/all.css" integrity="sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
    <%= stylesheet_pack_tag 'application' %>
 <!-- NEW! -->
    <title><%= meta_title %></title>
    <meta name="description" content="<%= meta_description %>">

    <!-- Facebook Open Graph data -->
    <meta property="og:title" content="<%= meta_title %>" />
    <meta property="og:type" content="website" />
    <meta property="og:url" content="<%= request.original_url %>" />
    <meta property="og:image" content="<%= meta_image %>" />
    <meta property="og:description" content="<%= meta_description %>" />
    <meta property="og:site_name" content="<%= meta_title %>" />

    <!-- Twitter Card data -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:title" content="<%= meta_title %>">
    <meta name="twitter:description" content="<%= meta_description %>">
    <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
    <meta name="twitter:image:src" content="<%= meta_image %>">


  <!-- NEW! -->
    <%= favicon_link_tag %>

  </head>
  <body>


    <% if user_signed_in? %>
        <div id="header">

    <%= render 'shared/navbar' %>
  </div>
    <%end%>
    <%= render 'shared/flashes' %>
    <%= javascript_pack_tag 'chart' %>

    <div class="yield-wrapper">
    <%= yield %>
        </div>

   <% if user_signed_in? %>
    <%= render 'shared/footer' %>

    <%end%>
    <%= javascript_pack_tag 'application' %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner col-xs-12" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.4) 0%, rgba(0,36,61,0.4) 50%), url(<%= image_path 'banner.jpg' %>);">
  <div class="banner-content">
    <h1>Welcome to</h1>
    <p><%= link_to root_path, class: "logo" do %>
           <%= image_tag "icon2.png", height: 100 %>
            <% end %></p>
            <% if current_user.nil? %>
    <a><%= link_to 'Sign up', new_user_registration_path, :class => "btn" %></a>
    <a><%= link_to 'Sign in',  new_user_session_path, :class => "btn"%></a>
    		<%  else  %>
    <a><%= link_to 'Start Saving',  balance_path, :class => "btn"%></a>
    <% end %>
  </div>
</div

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert" id="flash-notice">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
    <script>
    	setTimeout(()=> {
    		document.querySelector("#flash-notice").classList.add("disappear")
    	}, 1500);
    </script>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert" id='flash-alert'>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
    <script>
      setTimeout(()=> {
        document.querySelector("#flash-alert").classList.add("disappear")
      }, 1500);
    </script>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">

</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "bugetly.png", height: 40 %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right">

    <% if user_signed_in? %>

      <!-- Links when logged in -->

      <!-- Avatar with dropdown menu -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "narmeme.png", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to new_budget_path do %>
                <%= t(".add_a_new_budget", default: "Add a new budget") %>
              <% end %>
            </li>

            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>
    <% else %>
      <!-- Login link (when logged out) -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>
    <% end %>
  </div>

  <!-- Dropdown list appearing on mobile only -->

</div>

app/views/user_goals/new.html.erb
<div class="container new-goal-wrap">
  <p class="title">
    Hi <%=current_user.first_name%>,<br>what goal are you <br>saving for?
  </p>
  <div class="row">
    <div class="col col-xs-12 goal-form radio-inline">
      <%= simple_form_for [@user_goal] do |f| %>
        <%= f.input :goal_id, required: true, as: :radio_buttons, input_html: {class: "hide-checkbox"}, :label => '', :label_html => {:style => "width: auto; min-width:0; "}, collection: Goal.all.map { |g| [image_tag(g.image_goal), g.id] }, class: 'col-xs-4 image_goal' %>

        <%= f.input :amount_cents, label: false, error: 'This field is mandatory',  placeholder: 'Enter the amount ($)', as: :string, :input_html => { :value => "" }%>
        <%= f.button :submit, "Add", class: "submit_btn" %>
      <% end %>
    </div>
  </div>
</div>

<script>
  icon_divs = document.querySelectorAll('label');
  icon_divs.forEach((element) => {
    element.classList.add("icon-resting");
    element.addEventListener("click", ()=> {
      icon_divs.forEach(element => element.classList.remove('icon-active'));
      element.classList.add("icon-active");
    })
  })
</script>

app/views/user_goals/show.html.erb
<div class="container">
  <div class="row">
    <div class="col col-xs-12 ">

  <div class="info-goal">
  <h1>Hi, <%= @user_goal.user.first_name %>!</h1>
  <h2>Your <%= @user_goal.goal.name %> costs <%= @user_goal.amount_cents %>$. Start saving!</h2>
  </div>
  <div class="goal-chart">
  </div>

    </div>
  </div>
</div>

app/views/users/balance.html.erb
<div class="container">
  <div class="savings">
    <div class="col-xs-12">
      <!-- insert <div class="card"> -->
        <p id="title">Balance</p>
        <% if @user.balance < 0 %>
          <p id="balance-amount" class="negative-balance">$<%= @user.balance  %></p>
        <% else %>
          <p id="balance-amount" class="positive-balance">$<%= @user.balance  %></p>
        <% end %>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-6">
      <p>New Expense</p>
      <%= link_to new_budget_cash_flow_path(:budget_id) do%>
        <i class="fas fa-plus-circle"></i>
      <% end %>
    </div>
    <div class="col-xs-6">
      <p>Your Reports</p>
      <%= link_to dashboard_path do %>
        <i class="fas fa-chart-line"></i>
      <% end %>
    </div>
  </div>
</div>

app/views/users/dashboard.html.erb
    <div class="image_goal">
    <%= image_tag(@giphy_url.to_s, size: "360x200" ) %>

    </div>



    <div id="bar-2" class="bar-main-container emerald">
      <div class="goal_name">
         <span>Saved towards your <%= @goal.name %></span>
      </div>
      <div class="wrap">
        <div class="bar-percentage" data-percentage= <%= @goal_percent + 1 %> ></div>
        <div class="bar-container">
          <div class="bar"></div>
        </div>
      </div>
    </div>

 <!--      <div class="col-xs-6 col-sm-6">
        <div class="card">
          <div class="card-category">the first goal</div>
            <div class="card-description">
              <h2>$ <%= @user_goal.amount_cents%></h2>
              <p></p>
            </div>
          </div>
        </div> -->

<div class="budget-title">

    <p>My Budgets</p>

</div>
<div class="row dash-budgets">
  <% @budgets.each do |budget| %>
  <% @cash_flows = CashFlow.where(budget_id: budget.id)%>
  <div class="button-listener">
    <%= render 'components/budget_cards', budget: budget %>
      <div class="dropdown-content hidden">
        <%= render 'budgets/show', budget: budget, cash_flows: @cash_flows %>
      </div>
    </div>
    <%end%>
</div>

app/views/users/salary.html.erb
<div class="container new-goal-wrap">
      <p class="salary-title">What is your monthly income?</p>
	    <div class="row">
		 <div class="col col-xs-12 budget-fom">
			<%= simple_form_for @user, url: salary_path  do |f| %>
        	<%= f.input :salary,label:false, error: 'This field is mandatory',  placeholder: 'Enter your salary', as: :string %>
          <%= f.submit "Submit", :class => "submit_btn" %>
			<% end %>
		</div>
	</div>
</div>